server:
  port:
    8050

spring:
  application:    name: API-Gateway  cloud:    gateway:      routes:      - id: vendor
        uri: lb://vendor-service
        predicates:        - Path=/vendor/**
      - id: admin
        uri: lb://admin-service
        predicates:        - Path=/admin/**
      - id: catalog-service
        uri: lb://catalog-service
        predicates:
        - Path=/catalog-service/**
      - id: catalog-view
        uri: http://localhost:4210/catalog
        predicates:
        - Path=/catalog/**