server:
  port:
    8050

spring:
  application:    name: API-Gateway  cloud:    gateway:      routes:      - id: vendor
        uri: lb://vendor-service
        predicates:        - Path=/vendor/**
      - id: admin
        uri: lb://admin-service
        predicates:        - Path=/admin/**
      - id: catalog
        uri: lb://catalog-service
        predicates:
        - Path=/catalog/**
      - id: cart
        uri: lb://cart-service
        predicates:
        - Path=/cart/**